[package]
name = "codcel-parquet-engine"
version = "0.1.8"
edition = "2021"
authors = ["Codcel <support@codcel.com>"]
description = "Parquet table implementation for Codcel, providing Excel-like lookup and filter operations on Parquet files."
documentation = "https://codcel.io"
readme = "README.md"
license-file = "LICENSES/LICENSING.md"
repository = "https://github.com/codcel-io/codcel-parquet-engine"
homepage   = "https://codcel.io"
keywords = ["excel", "finance", "codcel", "spreadsheet", "functions"]
categories = ["mathematics", "finance"]

[dependencies]
codcel-calculation-engine = { git = "https://github.com/codcel-io/codcel-calculation-engine.git", branch = "pre-release-0.1.8" }
codcel-table-engine = { git = "https://github.com/codcel-io/codcel-table-engine.git", branch = "pre-release-0.1.8" }
async-trait = "0.1.89"
datafusion = "52.3.0"
tokio = { version = "1.50.0", features = ["sync", "time", "rt", "rt-multi-thread"] }
log = "0.4.29"
regex = "1.12.2"
once_cell = "1.21.3"
